// PBS Crewing Module: shared deterministic crew data generation

// ─── STCW Departments ───────────────────────────────────────────────
const STCW_DEPARTMENTS = [
    'Deck Department',
    'Engine Department',
    'Electro-Technical',
    'Catering / Hotel',
    'Radio / GMDSS',
    'Medical',
    'Safety & Survival',
];

// ─── STCW Ranks (per STCW Convention regulations) ───────────────────
const STCW_RANKS = [
    'II/2 – Master (≥ 3000 GT)',
    'II/2 – Chief Mate (≥ 3000 GT)',
    'II/3 – Master (< 3000 GT)',
    'II/3 – Chief Mate (< 3000 GT)',
    'II/3 – Master Near-Coastal (< 500 GT)',
    'II/1 – OOW Navigation (Second Officer)',
    'II/1 – OOW Navigation (Third Officer)',
    'II/4 – Rating Navigational Watch (Helmsman)',
    'II/5 – Able Seafarer Deck (AB)',
    'III/2 – Chief Engineer (≥ 3000 kW)',
    'III/2 – Second Engineer (≥ 3000 kW)',
    'III/3 – Chief Engineer (750–3000 kW)',
    'III/3 – Second Engineer (750–3000 kW)',
    'III/1 – EOOW (Third Engineer)',
    'III/1 – EOOW (Fourth Engineer)',
    'III/6 – Electro-Technical Officer (ETO)',
    'III/7 – Electro-Technical Rating (ETR)',
    'III/4 – Rating Engineering Watch (Oiler)',
    'III/5 – Able Seafarer Engine (Motorman)',
    'IV/2 – GMDSS Radio Operator',
    'Cadet – Deck (Trainee II/1)',
    'Cadet – Engine (Trainee III/1)',
];

// Real seafarer rows store short rank codes (backend/app/services/compliance_engine.py's
// RANK_FLEET_CAT, e.g. "2nd-mate") — the Rank filter dropdown's options are the long
// STCW_RANKS labels above, a different vocabulary. This translates a real short code to
// its closest STCW_RANKS label so the filter can match real data. "os"/"cook"/"steward"
// have no equivalent in STCW_RANKS at all (that list has no catering/OS entries) — left
// unmapped, same as any other genuinely-unmatched rank.
const RANK_CODE_TO_STCW_LABEL = {
    'master': 'II/2 – Master (≥ 3000 GT)',
    'chief-mate': 'II/2 – Chief Mate (≥ 3000 GT)',
    '2nd-mate': 'II/1 – OOW Navigation (Second Officer)',
    '3rd-mate': 'II/1 – OOW Navigation (Third Officer)',
    'bosun': 'II/4 – Rating Navigational Watch (Helmsman)',
    'ab': 'II/5 – Able Seafarer Deck (AB)',
    'deck-cadet': 'Cadet – Deck (Trainee II/1)',
    'gmdss-operator': 'IV/2 – GMDSS Radio Operator',
    'chief-engineer': 'III/2 – Chief Engineer (≥ 3000 kW)',
    '2nd-engineer': 'III/2 – Second Engineer (≥ 3000 kW)',
    '3rd-engineer': 'III/1 – EOOW (Third Engineer)',
    '4th-engineer': 'III/1 – EOOW (Fourth Engineer)',
    'eto': 'III/6 – Electro-Technical Officer (ETO)',
    'ase': 'III/5 – Able Seafarer Engine (Motorman)',
    'oiler': 'III/4 – Rating Engineering Watch (Oiler)',
    'etr': 'III/7 – Electro-Technical Rating (ETR)',
    'engine-cadet': 'Cadet – Engine (Trainee III/1)',
};

// ─── Nationality (Americas) ────────────────────────────────────────
const NATIONALITIES_AMERICAS = [
    'Panama', 'Colombia', 'Peru', 'Ecuador', 'Mexico', 'Brazil', 'Chile',
    'Argentina', 'Venezuela', 'Honduras', 'Guatemala', 'Dominican Republic',
    'Costa Rica', 'Cuba', 'El Salvador', 'Nicaragua', 'Bolivia', 'Paraguay',
    'Uruguay', 'United States', 'Canada',
];

// ISO 3166-1 alpha-2 codes for flag SVG file lookup. Covers ~250 countries/
// territories (all flags in assets/flags/) — broad on purpose: our target
// market is the Americas, but maritime crews are routinely international, so
// nationality resolution shouldn't be limited to the ~21-country pool used
// for fake-data generation (NATIONALITIES_AMERICAS, below).
const COUNTRY_CODE_MAP = {
    'Afghanistan': 'af',
    'Åland Islands': 'ax',
    'Albania': 'al',
    'Algeria': 'dz',
    'American Samoa': 'as',
    'Andorra': 'ad',
    'Angola': 'ao',
    'Anguilla': 'ai',
    'Antarctica': 'aq',
    'Antigua and Barbuda': 'ag',
    'Argentina': 'ar',
    'Armenia': 'am',
    'Aruba': 'aw',
    'Australia': 'au',
    'Austria': 'at',
    'Azerbaijan': 'az',
    'Bahamas': 'bs',
    'Bahrain': 'bh',
    'Bangladesh': 'bd',
    'Barbados': 'bb',
    'Belarus': 'by',
    'Belgium': 'be',
    'Belize': 'bz',
    'Benin': 'bj',
    'Bermuda': 'bm',
    'Bhutan': 'bt',
    'Bolivia': 'bo',
    'Bonaire, Sint Eustatius and Saba': 'bq',
    'Bosnia and Herzegovina': 'ba',
    'Botswana': 'bw',
    'Bouvet Island': 'bv',
    'Brazil': 'br',
    'British Indian Ocean Territory': 'io',
    'Brunei': 'bn',
    'Bulgaria': 'bg',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',
    'Cambodia': 'kh',
    'Cameroon': 'cm',
    'Canada': 'ca',
    'Cape Verde': 'cv',
    'Cayman Islands': 'ky',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Chile': 'cl',
    'China': 'cn',
    'Christmas Island': 'cx',
    'Cocos (Keeling) Islands': 'cc',
    'Colombia': 'co',
    'Comoros': 'km',
    'Congo': 'cg',
    'Cook Islands': 'ck',
    'Costa Rica': 'cr',
    'Croatia': 'hr',
    'Cuba': 'cu',
    'Curaçao': 'cw',
    'Cyprus': 'cy',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Djibouti': 'dj',
    'Dominica': 'dm',
    'Dominican Republic': 'do',
    'DR Congo': 'cd',
    'East Timor': 'tl',
    'Ecuador': 'ec',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Equatorial Guinea': 'gq',
    'Eritrea': 'er',
    'Estonia': 'ee',
    'Eswatini': 'sz',
    'Ethiopia': 'et',
    'Falkland Islands (Malvinas)': 'fk',
    'Faroe Islands': 'fo',
    'Fiji': 'fj',
    'Finland': 'fi',
    'France': 'fr',
    'French Guiana': 'gf',
    'French Polynesia': 'pf',
    'French Southern Territories': 'tf',
    'Gabon': 'ga',
    'Gambia': 'gm',
    'Georgia': 'ge',
    'Germany': 'de',
    'Ghana': 'gh',
    'Gibraltar': 'gi',
    'Greece': 'gr',
    'Greenland': 'gl',
    'Grenada': 'gd',
    'Guadeloupe': 'gp',
    'Guam': 'gu',
    'Guatemala': 'gt',
    'Guernsey': 'gg',
    'Guinea': 'gn',
    'Guinea-Bissau': 'gw',
    'Guyana': 'gy',
    'Haiti': 'ht',
    'Heard Island and McDonald Islands': 'hm',
    'Honduras': 'hn',
    'Hong Kong': 'hk',
    'Hungary': 'hu',
    'Iceland': 'is',
    'India': 'in',
    'Indonesia': 'id',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Ireland': 'ie',
    'Isle of Man': 'im',
    'Israel': 'il',
    'Italy': 'it',
    'Ivory Coast': 'ci',
    'Jamaica': 'jm',
    'Japan': 'jp',
    'Jersey': 'je',
    'Jordan': 'jo',
    'Kazakhstan': 'kz',
    'Kenya': 'ke',
    'Kiribati': 'ki',
    'Kosovo': 'xk',
    'Kuwait': 'kw',
    'Kyrgyzstan': 'kg',
    'Laos': 'la',
    'Latvia': 'lv',
    'Lebanon': 'lb',
    'Lesotho': 'ls',
    'Liberia': 'lr',
    'Libya': 'ly',
    'Liechtenstein': 'li',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Macau': 'mo',
    'Madagascar': 'mg',
    'Malawi': 'mw',
    'Malaysia': 'my',
    'Maldives': 'mv',
    'Mali': 'ml',
    'Malta': 'mt',
    'Marshall Islands': 'mh',
    'Martinique': 'mq',
    'Mauritania': 'mr',
    'Mauritius': 'mu',
    'Mayotte': 'yt',
    'Mexico': 'mx',
    'Micronesia': 'fm',
    'Moldova': 'md',
    'Monaco': 'mc',
    'Mongolia': 'mn',
    'Montenegro': 'me',
    'Montserrat': 'ms',
    'Morocco': 'ma',
    'Mozambique': 'mz',
    'Myanmar': 'mm',
    'Namibia': 'na',
    'Nauru': 'nr',
    'Nepal': 'np',
    'Netherlands': 'nl',
    'New Caledonia': 'nc',
    'New Zealand': 'nz',
    'Nicaragua': 'ni',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Niue': 'nu',
    'Norfolk Island': 'nf',
    'North Korea': 'kp',
    'North Macedonia': 'mk',
    'Northern Mariana Islands': 'mp',
    'Norway': 'no',
    'Oman': 'om',
    'Pakistan': 'pk',
    'Palau': 'pw',
    'Palestine': 'ps',
    'Panama': 'pa',
    'Papua New Guinea': 'pg',
    'Paraguay': 'py',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Pitcairn': 'pn',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Puerto Rico': 'pr',
    'Qatar': 'qa',
    'Reunion': 're',
    'Romania': 'ro',
    'Russia': 'ru',
    'Rwanda': 'rw',
    'Saint Barthélemy': 'bl',
    'Saint Helena': 'sh',
    'Saint Kitts and Nevis': 'kn',
    'Saint Lucia': 'lc',
    'Saint Martin (French part)': 'mf',
    'Saint Pierre and Miquelon': 'pm',
    'Saint Vincent and the Grenadines': 'vc',
    'Samoa': 'ws',
    'San Marino': 'sm',
    'Sao Tome and Principe': 'st',
    'Saudi Arabia': 'sa',
    'Senegal': 'sn',
    'Serbia': 'rs',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Singapore': 'sg',
    'Sint Maarten (Dutch part)': 'sx',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'Solomon Islands': 'sb',
    'Somalia': 'so',
    'South Africa': 'za',
    'South Georgia and the South Sandwich Islands': 'gs',
    'South Korea': 'kr',
    'South Sudan': 'ss',
    'Spain': 'es',
    'Sri Lanka': 'lk',
    'Sudan': 'sd',
    'Suriname': 'sr',
    'Svalbard and Jan Mayen': 'sj',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Syria': 'sy',
    'Taiwan': 'tw',
    'Tajikistan': 'tj',
    'Tanzania': 'tz',
    'Thailand': 'th',
    'Togo': 'tg',
    'Tokelau': 'tk',
    'Tonga': 'to',
    'Trinidad and Tobago': 'tt',
    'Tunisia': 'tn',
    'Türkiye': 'tr',
    'Turkmenistan': 'tm',
    'Turks and Caicos Islands': 'tc',
    'Tuvalu': 'tv',
    'Uganda': 'ug',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom': 'gb',
    'United States': 'us',
    'United States Minor Outlying Islands': 'um',
    'Uruguay': 'uy',
    'Uzbekistan': 'uz',
    'Vanuatu': 'vu',
    'Vatican City': 'va',
    'Venezuela': 've',
    'Vietnam': 'vn',
    'Virgin Islands, British': 'vg',
    'Virgin Islands, U.S.': 'vi',
    'Wallis and Futuna': 'wf',
    'Western Sahara': 'eh',
    'Yemen': 'ye',
    'Zambia': 'zm',
    'Zimbabwe': 'zw',
};

// Reverse of COUNTRY_CODE_MAP (code -> name), for resolving a real seafarer's
// `nationalities` array — Castor stores each entry as an ISO2 code (e.g. "PA"),
// not the full name `nationality` (singular) uses (e.g. "Panama").
const ISO2_TO_COUNTRY_NAME = Object.fromEntries(
    Object.entries(COUNTRY_CODE_MAP).map(([name, code]) => [code.toUpperCase(), name])
);

// A seafarer can have up to 3 nationalities (Castor's MyProfile "Nacionalidades"
// picker) — `nationalities` (plural, ISO2 codes) and `nationality` (singular,
// full name, set at registration and never re-derived afterward) are
// independent columns that can diverge; either format can show up here
// depending on which one a given seafarer/card actually has. Resolves either
// into a consistent {name, flagPath} shape, `flagPath: null` when unknown.
const resolveNationalityEntry = (entry) => {
    if (typeof entry !== 'string' || entry.length === 0) return null;
    if (/^[A-Za-z]{2}$/.test(entry)) {
        const code = entry.toUpperCase();
        return { name: ISO2_TO_COUNTRY_NAME[code] || code, flagPath: getCrewFlagPath(ISO2_TO_COUNTRY_NAME[code] || null) };
    }
    return { name: entry, flagPath: getCrewFlagPath(entry) };
};

// ─── Flags ───────────────────────────────────────────────────────
const getCrewFlagPath = (nationality) => {
    const code = COUNTRY_CODE_MAP[nationality];
    return code ? `flags/${code}.svg` : null;
};

module.exports = {
    getCrewFlagPath,
    STCW_DEPARTMENTS,
    STCW_RANKS,
    NATIONALITIES_AMERICAS,
    COUNTRY_CODE_MAP,
    RANK_CODE_TO_STCW_LABEL,
    ISO2_TO_COUNTRY_NAME,
    resolveNationalityEntry,
};
