// PBS Crewing Module: STCW IMO Course & Exam data
// Based on STCW Convention (Manila Amendments 2010) and IMO Model Course catalogue

const STCW_LEVELS = ['All Levels', 'Ratings', 'OOW', 'Management'];

const EXAM_DEPARTMENTS = [
    'All Departments',
    'Deck Department',
    'Engine Department',
    'Electro-Technical',
    'Radio / GMDSS',
    'Medical',
    'Catering / Hotel',
];

const EXAMS = [
    // ─── COMMON (All Levels, STCW Chapter VI) ─────────────────────────
    {
        id: 'imo-1.19',
        name: 'Personal Survival Techniques',
        code: 'IMO 1.19',
        stcwRef: 'A-VI/1-1',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Survival at sea: life rafts, lifejackets, cold water survival, helicopter rescue procedures.',
        duration: '1 day',
        validity: '5 years',
    },
    {
        id: 'imo-1.20',
        name: 'Fire Prevention and Fire Fighting',
        code: 'IMO 1.20',
        stcwRef: 'A-VI/1-2',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Use of fire extinguishers, breathing apparatus, fire-fighting equipment and emergency procedures.',
        duration: '1.5 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.13',
        name: 'Elementary First Aid',
        code: 'IMO 1.13',
        stcwRef: 'A-VI/1-3',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Immediate first aid procedures for accidents and illness on board.',
        duration: '1 day',
        validity: '5 years',
    },
    {
        id: 'imo-1.21',
        name: 'Personal Safety and Social Responsibilities',
        code: 'IMO 1.21',
        stcwRef: 'A-VI/1-4',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Shipboard safety, pollution prevention, communication, and human relationships.',
        duration: '1 day',
        validity: '5 years',
    },
    {
        id: 'imo-3.27',
        name: 'Security Awareness Training (ISPS)',
        code: 'IMO 3.27',
        stcwRef: 'A-VI/6-1',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'ISPS Code awareness, recognizing security threats, ship security procedures.',
        duration: '0.5 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.23',
        name: 'Proficiency in Survival Craft and Rescue Boats',
        code: 'IMO 1.23',
        stcwRef: 'A-VI/2-1',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Launching and handling survival craft, rescue boats, and on-board survival procedures.',
        duration: '2 days',
        validity: '5 years',
    },
    {
        id: 'imo-2.03',
        name: 'Advanced Fire Fighting',
        code: 'IMO 2.03',
        stcwRef: 'A-VI/3',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Fire-fighting organization, tactics, command and control during fire emergencies.',
        duration: '3 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.14',
        name: 'Medical First Aid',
        code: 'IMO 1.14',
        stcwRef: 'A-VI/4-1',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical'],
        description: 'Medical care on board, use of medical guide, and radio medical advice procedures.',
        duration: '2 days',
        validity: '5 years',
    },
    {
        id: 'imo-3.17',
        name: 'Maritime English',
        code: 'IMO 3.17',
        stcwRef: 'A-II/1, A-III/1',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS'],
        description: 'IMO Standard Marine Communication Phrases (SMCP), bridge-to-bridge communication, VHF procedures.',
        duration: '5 days',
        validity: '5 years',
    },
    {
        id: 'marlins-test',
        name: 'Marlins English Language Test',
        code: 'MARLINS',
        stcwRef: 'Industry Standard',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Standardised online test of English for seafarers. Covers listening, grammar, vocabulary, and reading comprehension for maritime operations.',
        duration: '0.5 days',
        validity: '1 year',
    },
    {
        id: 'eng-proficiency',
        name: 'English Proficiency for Seafarers',
        code: 'STCW B-I/12',
        stcwRef: 'B-I/12',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Assessment of English language skills required by STCW for effective communication on board, including emergency situations.',
        duration: '1 day',
        validity: '2 years',
    },
    {
        id: 'basic-maritime',
        name: 'Basic Maritime Knowledge',
        code: 'PBS-BMK',
        stcwRef: 'Pre-sea',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Catering / Hotel'],
        description: 'Introduction to ship types, maritime terminology, shipboard organisation, safety culture, and basic seamanship for new entrants.',
        duration: '3 days',
        validity: 'Certificate of Completion',
    },
    {
        id: 'env-awareness',
        name: 'Environmental Awareness Training (MARPOL)',
        code: 'MARPOL',
        stcwRef: 'MARPOL 73/78',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Catering / Hotel'],
        description: 'MARPOL regulations, garbage management, oil record book, ballast water management, and emission control areas.',
        duration: '1 day',
        validity: '5 years',
    },
    {
        id: 'cyber-security',
        name: 'Maritime Cyber Security Awareness',
        code: 'IMO MSC.428',
        stcwRef: 'ISM Code',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS'],
        description: 'Cyber risk management on board, ECDIS and AIS vulnerabilities, phishing, network security best practices per IMO guidelines.',
        duration: '0.5 days',
        validity: '2 years',
    },
    {
        id: 'drug-alcohol',
        name: 'Drug and Alcohol Awareness',
        code: 'MLC 4.3',
        stcwRef: 'MLC 2006',
        level: 'All Levels',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical', 'Radio / GMDSS', 'Medical', 'Catering / Hotel'],
        description: 'Company drug and alcohol policy, testing procedures, effects on performance, and legal consequences under MLC 2006.',
        duration: '0.5 days',
        validity: '2 years',
    },

    // ─── RATINGS (STCW Chapter II/III support level) ──────────────────
    {
        id: 'imo-7.15',
        name: 'Rating Forming Part of a Navigational Watch',
        code: 'IMO 7.15',
        stcwRef: 'A-II/4',
        level: 'Ratings',
        departments: ['Deck Department'],
        description: 'Lookout duties, helm orders, basic navigation watch duties under supervision.',
        duration: '5 days',
        validity: 'Certificate of Competency',
    },
    {
        id: 'imo-7.03r',
        name: 'Able Seafarer Deck',
        code: 'IMO 7.03',
        stcwRef: 'A-II/5',
        level: 'Ratings',
        departments: ['Deck Department'],
        description: 'Navigation watchkeeping at support level, cargo handling, mooring, and steering.',
        duration: '10 days',
        validity: 'Certificate of Competency',
    },
    {
        id: 'imo-7.16',
        name: 'Rating Forming Part of an Engineering Watch',
        code: 'IMO 7.16',
        stcwRef: 'A-III/4',
        level: 'Ratings',
        departments: ['Engine Department'],
        description: 'Engine room watch duties, machinery operation under supervision.',
        duration: '5 days',
        validity: 'Certificate of Competency',
    },
    {
        id: 'imo-7.04r',
        name: 'Able Seafarer Engine',
        code: 'IMO 7.04',
        stcwRef: 'A-III/5',
        level: 'Ratings',
        departments: ['Engine Department'],
        description: 'Engine room watchkeeping at support level, maintenance of machinery and systems.',
        duration: '10 days',
        validity: 'Certificate of Competency',
    },
    {
        id: 'imo-etr',
        name: 'Electro-Technical Rating (ETR)',
        code: 'STCW A-III/7',
        stcwRef: 'A-III/7',
        level: 'Ratings',
        departments: ['Electro-Technical'],
        description: 'Electrical systems maintenance at support level, safe working with high voltage.',
        duration: '10 days',
        validity: 'Certificate of Competency',
    },
    {
        id: 'imo-1.33',
        name: "Ship's Cook Certificate",
        code: 'IMO 1.33',
        stcwRef: 'MLC 3.2',
        level: 'Ratings',
        departments: ['Catering / Hotel'],
        description: 'Food safety, nutrition, large-scale cooking, hygiene standards per MLC 2006.',
        duration: '5 days',
        validity: 'Certificate of Competency',
    },

    // ─── OOW (Operational level officers) ─────────────────────────────
    {
        id: 'imo-oow-nav',
        name: 'Officer in Charge of a Navigational Watch',
        code: 'IMO 7.03',
        stcwRef: 'A-II/1',
        level: 'OOW',
        departments: ['Deck Department'],
        description: 'Celestial and terrestrial navigation, watchkeeping, collision regulations, cargo, and stability.',
        duration: '20 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.07',
        name: 'Radar Navigation, Radar Plotting and Use of ARPA',
        code: 'IMO 1.07',
        stcwRef: 'A-II/1',
        level: 'OOW',
        departments: ['Deck Department'],
        description: 'Radar operation, target tracking, automatic radar plotting aids, collision avoidance.',
        duration: '5 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.27',
        name: 'ECDIS – Electronic Chart Display',
        code: 'IMO 1.27',
        stcwRef: 'A-II/1',
        level: 'OOW',
        departments: ['Deck Department'],
        description: 'Operation of ECDIS, chart updating, route planning using electronic charts.',
        duration: '5 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.22',
        name: 'Bridge Resource Management (BRM)',
        code: 'IMO 1.22',
        stcwRef: 'A-II/1',
        level: 'OOW',
        departments: ['Deck Department'],
        description: 'Team coordination on bridge, situational awareness, decision-making, fatigue management.',
        duration: '3 days',
        validity: '5 years',
    },
    {
        id: 'imo-oow-eng',
        name: 'Officer in Charge of an Engineering Watch',
        code: 'IMO 7.04',
        stcwRef: 'A-III/1',
        level: 'OOW',
        departments: ['Engine Department'],
        description: 'Main and auxiliary machinery operation, watchkeeping, bunkering, maintenance planning.',
        duration: '20 days',
        validity: '5 years',
    },
    {
        id: 'imo-2.07',
        name: 'Engine Room Resource Management (ERM)',
        code: 'IMO 2.07',
        stcwRef: 'A-III/1',
        level: 'OOW',
        departments: ['Engine Department'],
        description: 'Team leadership in engine room, workload management, communication protocols.',
        duration: '3 days',
        validity: '5 years',
    },
    {
        id: 'imo-eto',
        name: 'Electro-Technical Officer (ETO)',
        code: 'STCW A-III/6',
        stcwRef: 'A-III/6',
        level: 'OOW',
        departments: ['Electro-Technical'],
        description: 'Electrical, electronic, and control systems at operational level; high voltage safety.',
        duration: '15 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.25',
        name: 'GMDSS General Operator Certificate (GOC)',
        code: 'IMO 1.25',
        stcwRef: 'A-IV/2',
        level: 'OOW',
        departments: ['Radio / GMDSS'],
        description: 'Global Maritime Distress and Safety System operation, DSC, INMARSAT, NAVTEX, EPIRB.',
        duration: '10 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.15',
        name: 'Medical Care on Board Ships',
        code: 'IMO 1.15',
        stcwRef: 'A-VI/4-2',
        level: 'OOW',
        departments: ['Medical', 'Deck Department', 'Engine Department'],
        description: 'Extended medical care, diagnosis, treatment, pharmacy management, radio medical advice.',
        duration: '5 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.01',
        name: 'Basic Oil and Chemical Tanker Cargo Operations',
        code: 'IMO 1.01',
        stcwRef: 'A-V/1-1-1',
        level: 'OOW',
        departments: ['Deck Department', 'Engine Department'],
        description: 'Safe handling of oil/chemical cargoes, tank cleaning, inerting, and COW at basic level.',
        duration: '3 days',
        validity: '5 years',
    },

    // ─── MANAGEMENT (Senior officers) ─────────────────────────────────
    {
        id: 'imo-7.01',
        name: 'Master and Chief Mate (≥ 3000 GT)',
        code: 'IMO 7.01',
        stcwRef: 'A-II/2',
        level: 'Management',
        departments: ['Deck Department'],
        description: 'Voyage planning, ship stability, cargo operations, and emergency response at management level.',
        duration: '30 days',
        validity: '5 years',
    },
    {
        id: 'imo-7.02',
        name: 'Chief Engineer and Second Engineer (≥ 3000 kW)',
        code: 'IMO 7.02',
        stcwRef: 'A-III/2',
        level: 'Management',
        departments: ['Engine Department'],
        description: 'Management of propulsion and machinery, fuel management, dry-docking, planned maintenance.',
        duration: '30 days',
        validity: '5 years',
    },
    {
        id: 'imo-brm-mgmt',
        name: 'Ship Simulation and Bridge Teamwork (Management)',
        code: 'IMO 1.22',
        stcwRef: 'A-II/2',
        level: 'Management',
        departments: ['Deck Department'],
        description: 'Advanced BRM for Masters and Chief Mates, crisis management, passage planning leadership.',
        duration: '5 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.02',
        name: 'Advanced Training for Oil Tanker Cargo Operations',
        code: 'IMO 1.02',
        stcwRef: 'A-V/1-1-2',
        level: 'Management',
        departments: ['Deck Department', 'Engine Department'],
        description: 'Oil tanker management, COW, IGS, loading/discharge planning, emergency command.',
        duration: '5 days',
        validity: '5 years',
    },
    {
        id: 'imo-1.06',
        name: 'Advanced Training for Liquefied Gas Tanker Operations',
        code: 'IMO 1.06',
        stcwRef: 'A-V/1-2-2',
        level: 'Management',
        departments: ['Deck Department', 'Engine Department'],
        description: 'LNG/LPG cargo management, re-liquefaction, boil-off gas handling, cargo calculations.',
        duration: '5 days',
        validity: '5 years',
    },
    {
        id: 'imo-leadership',
        name: 'Leadership and Teamwork',
        code: 'STCW A-II/2',
        stcwRef: 'A-II/2, A-III/2',
        level: 'Management',
        departments: ['Deck Department', 'Engine Department', 'Electro-Technical'],
        description: 'Shipboard leadership, management skills, decision-making, authority and motivation.',
        duration: '3 days',
        validity: '5 years',
    },
];

// ─── Rank → required exam IDs mapping ────────────────────────────────
// Based on STCW regulations per rank. "All Levels" exams are required
// for every rank (basic safety). Rank-specific exams are additive.
const RANK_REQUIRED_EXAMS = {
    master: [
        /* All Levels */ 'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23', 'imo-2.03', 'imo-1.14',
        /* OOW deck */ 'imo-oow-nav', 'imo-1.07', 'imo-1.27', 'imo-1.22',
        /* Management deck */ 'imo-7.01', 'imo-brm-mgmt',
        /* GMDSS */ 'imo-1.25',
        /* Medical */ 'imo-1.15',
        /* Leadership */ 'imo-leadership',
    ],
    'chief-officer': [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23', 'imo-2.03', 'imo-1.14',
        'imo-oow-nav', 'imo-1.07', 'imo-1.27', 'imo-1.22',
        'imo-7.01', 'imo-brm-mgmt',
        'imo-1.25', 'imo-1.15', 'imo-leadership',
    ],
    '2nd-officer': [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23', 'imo-2.03', 'imo-1.14',
        'imo-oow-nav', 'imo-1.07', 'imo-1.27', 'imo-1.22',
        'imo-1.25',
    ],
    '3rd-officer': [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23', 'imo-2.03',
        'imo-oow-nav', 'imo-1.27',
    ],
    'chief-engineer': [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23', 'imo-2.03', 'imo-1.14',
        'imo-oow-eng', 'imo-2.07',
        'imo-7.02', 'imo-1.15', 'imo-leadership',
    ],
    '2nd-engineer': [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23', 'imo-2.03',
        'imo-oow-eng', 'imo-2.07',
        'imo-7.02', 'imo-leadership',
    ],
    electrician: [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23', 'imo-2.03',
        'imo-eto', 'imo-etr',
    ],
    bosun: [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23',
        'imo-7.15', 'imo-7.03r',
    ],
    ab: [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27', 'imo-1.23',
        'imo-7.15', 'imo-7.03r',
    ],
    cook: [
        'imo-1.19', 'imo-1.20', 'imo-1.13', 'imo-1.21', 'imo-3.27',
        'imo-1.33',
    ],
};

module.exports = { EXAMS, STCW_LEVELS, EXAM_DEPARTMENTS, RANK_REQUIRED_EXAMS };
